[package]
name = "security"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.38.4"
winreg = "0.56.0"
windows-service = "0.8.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Foundation",
    "Win32_System_Services",
    "Win32_NetworkManagement_NetManagement",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemInformation",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_Shutdown",
    "Win32_Security"
]